version: '3.1'

services:

  elasticsearch:
   container_name: elasticsearch
   restart: always
   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   networks:
    - insurance

  kibana:
   container_name: kibana
   restart: always
   image: docker.elastic.co/kibana/kibana:7.9.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
   networks:
    - insurance
    
  mssql:
   container_name: mssql
   restart: always
   image: mcr.microsoft.com/mssql/server:2019-latest
   ports:
    - 14333:1433
   environment:
    - SA_PASSWORD=halil12345;
    - ACCEPT_EULA=Y
    - MSSQL_PID=Developer 
   networks:
    - insurance    

  insurance: 
    build: 
      context: .
      dockerfile: Dockerfile.insurance
    image: insurance
    container_name: insurance
    hostname: insurance
    restart: always
    ports:
      - 5001:80
    environment:
     - ProductApiConfiguration:BaseAddress=http://product
     - "ConnectionStrings:InsuranceDbContext=Server=mssql;Database=Insurance;User Id=sa;Password=\"halil12345;\";Persist Security Info=True;"
     - Elasticsearch=http://elasticsearch:9200
     - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
     - mssql
    networks:
     - insurance
    
  product: 
    build: 
      context: .
      dockerfile: Dockerfile.product
    image: product
    container_name: product
    hostname: product
    restart: always
    ports:
      - 5002:80
    networks:
     - insurance
    
networks:
  insurance:
    driver: bridge

volumes:
  elasticsearch-data: