// <auto-generated />
using Insurance.Data.Database.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Insurance.Data.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20201023183436_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("Insurance.Data.Domain.InsuranceProductTypeRule", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("InsuranceCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductTypeId", "Type");

                    b.ToTable("InsuranceProductTypeRules");

                    b.HasData(
                        new
                        {
                            ProductTypeId = 21,
                            Type = 1,
                            InsuranceCost = 500m
                        },
                        new
                        {
                            ProductTypeId = 32,
                            Type = 1,
                            InsuranceCost = 500m
                        },
                        new
                        {
                            ProductTypeId = 33,
                            Type = 2,
                            InsuranceCost = 500m
                        });
                });

            modelBuilder.Entity("Insurance.Data.Domain.InsuranceRangeRule", b =>
                {
                    b.Property<int>("InsuranceRangeRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("ExclusiveMaxSalePrice")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("InclusiveMinSalePrice")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("InsuranceCost")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("InsuranceRangeRuleId");

                    b.ToTable("InsuranceRangeRules");

                    b.HasData(
                        new
                        {
                            InsuranceRangeRuleId = 1,
                            ExclusiveMaxSalePrice = 2000m,
                            InclusiveMinSalePrice = 500m,
                            InsuranceCost = 1000m
                        },
                        new
                        {
                            InsuranceRangeRuleId = 2,
                            ExclusiveMaxSalePrice = 9999999.99m,
                            InclusiveMinSalePrice = 2000m,
                            InsuranceCost = 1000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
