// <auto-generated />
using Insurance.Data.Database.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Insurance.Data.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20201021200254_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("Insurance.Data.Domain.InsuranceProductTypeRule", b =>
                {
                    b.Property<int>("InsuranceProductTypeRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("InsuranceCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("InsuranceProductTypeRuleId");

                    b.ToTable("InsuranceProductTypeRules");
                });

            modelBuilder.Entity("Insurance.Data.Domain.InsuranceRangeRule", b =>
                {
                    b.Property<int>("InsuranceRangeRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("ExclusiveMaxSalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InclusiveMinSalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsuranceCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InsuranceRangeRuleId");

                    b.ToTable("InsuranceRangeRules");
                });
#pragma warning restore 612, 618
        }
    }
}
